export const IS_LOGGED_IN = 'IS_LOGGED_IN';

export const ADD_TO_CART = 'ADD_TO_CART';
export const SET_TOP_DEALS = 'SET_TOP_DEALS';
export const SET_TOP_SELLERS = 'SET_TOP_SELLERS';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_BANNERS = 'SET_BANNERS';


export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_RENDER_KEY = 'CART_RENDER_KEY';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREARSE_QUANTITY = 'DECREARSE_QUANTITY';
export const EMPTY_THE_CART = 'EMPTY_THE_CART'
